# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously during install.
# If you're behind an auth proxy or do not have network access, this can hang.
# For details, see https://guides.cocoapods.org/usage/faq.html#can-i-disable-cocoapods-analytics
install! 'cocoapods', :deterministic_uuids => false

# Flutter link settings
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Agora RTC engine and other modern plugins require a higher deployment target
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
